### ISSUE TITLE
Trimmomatic wrapper bug

### ISSUE THREAD

**Issue by dpryan79** [fls-bioinformatics-core/galaxy-tools#24]
Can you quotes the two instances of `$@` in trimmomatic.sh? This would allow for paths that include spaces. As is, we can't link fastq files into Galaxy and use trimmomatic if they have a path like "/there are spaces/sample.fastq.gz". Using `"$@"` instead of `$@` fixes this.

**Comment by pjbriggs** [comment]
Hello @dpryan79 

Thanks for reporting this issue, I can see there will be a problem when using paths containing spaces.

As you suggest, quoting the arguments in the wrapper shell script would address this problem. However as part of trying to make the tool compatible with Galaxy's conda dependency resolver, I'm planning to drop the shell script completely - the changes are currently in PR #23.

With these changes all file paths should be quoted, so hopefully this problem will go away. However if you are able to review the changes perhaps you can comment if you see any pitfalls.

HTH

Peter

**Comment by dpryan79** [comment]
:+1:  Anything that gets away from the shell script should resolve the problem.

**Comment by pjbriggs** [comment]
@dpryan79 sorry this took a lot longer to than anticipated due to other commitments, however the conda-compatibility updates have now been finished and pushed to the toolsheds (PR #23).

As part of this the wrapper script has been purged, and the inputs and outputs are now quoted. So hopefully this addresses your issue.

**Comment by dpryan79** [comment]
+1
