### ISSUE TITLE
cistrome BETA

### ISSUE THREAD

**Issue by jj-umn** [fls-bioinformatics-core/galaxy-tools#54]
I've added a bioconda package for cistrome_beta and updated the Galaxy tools for Cistrome BETA at: 
https://github.com/jj-umn/galaxytools/tree/master/cistrome_beta  and updated them in the testtoolshed: https://testtoolshed.g2.bx.psu.edu/view/jjohnson/cistrome_beta/52ed4957ace9

I'm looking for a new home for them before putting them in the main toolshed.   Is this something you would want to adopt, or should I see if the IUC is willing to maintain these?
Thanks,
JJ

**Comment by jj-umn** [comment]
@pjbriggs I should have directed this cistrome BETA option to you.

**Comment by pjbriggs** [comment]
Hi @jj-umn  - thanks for getting in touch. Unfortunately I don't think I'll be able to adopt these tools, the group I work for don't use Cistrome (beyond the Cistrome version of CEAS, which we use in preference to the canonical version because it supports bigWig files) so I wouldn't really be able to justify time spent on maintaining them. Hopefully the IUC can pick them up.

Best wishes, Peter
