### ISSUE TITLE
Trimmomatic: move tool to IUC

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/galaxy-tools#91]
Proposal to move the `trimmomatic` tool to the IUC tool repository (https://github.com/galaxyproject/tools-iuc), based on discussion with @bernt-matthias in PR #90.

**Comment by bernt-matthias** [comment]
I would not change the owner but leave it as is. Instead you can grant the IUC the permission to push to the original TS repo. 

For widely used used tools changing the owner would create to much confusion, since  `iuc/trimmomatic ` would be treated as a different too (ie. it would destroy the tool lineage).

**Comment by pjbriggs** [comment]
Thanks - I've now created the PR at https://github.com/galaxyproject/tools-iuc/pull/5698

As noted there, I've kept `pjbriggs` as the owner but IUC should now also have permission to administer the tool on the toolshed (I wasn't able to access the test toolshed to also make the change there, however maybe that's not important).

There's also a new PR #92 in this repo which moves the tool to the `legacy` dir in anticipation of the transfer to the IUC repo.

Thanks for all your help so far @bernt-matthias! Please let me know if there's anything else I need to do at this stage.

**Comment by pjbriggs** [comment]
Trimmomatic now relocated to IUC tools repository, and files moved to legacy in this repository.
